imagePullSecrets:
  - name: hhk7734-ghcr
frontend:
  image:
    repository: ghcr.io/hhk7734/wiki
    tag: "205de3e"
  resources:
    requests:
      memory: 10Mi
    limits:
      memory: 64Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                  - "true"
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
